[build]
builder = "nixpacks"
buildCommand = "pip install flask requests" # Kütüphaneleri buraya ekledik

[deploy]
startCommand = "python app.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
